# Dev image with Maven and JDK
FROM maven:3.9-eclipse-temurin-17

WORKDIR /app

# pre-fetch dependencies
# COPY pom.xml .
# RUN mvn dependency:go-offline

# Start command
CMD ["mvn", "spring-boot:run", "-Plocal"]
