# Build stage
FROM maven:3.9-eclipse-temurin-21 AS builder
WORKDIR /app

# Copy pom first to leverage Docker cache for dependency download
COPY pom.xml .
# If you have settings.xml, copy it too: COPY .mvn/settings.xml /root/.m2/settings.xml
RUN mvn -B dependency:go-offline

# Copy sources and build
COPY src ./src
RUN mvn -B -Pprod -DskipTests package

# Runtime
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8080


# Default JVM + Spring profile (can be overridden)
# ENV JAVA_OPTS="-Xms512m -Xmx1024m"
# ENV SPRING_PROFILES_ACTIVE=prod

ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar /app/app.jar"] # JAVA_OPTS => "-Xms512m -Xmx1024m" = min heap -> max heap
