# Dev image with Maven and JDK
FROM maven:3.9-eclipse-temurin-21

WORKDIR /app

# pre-fetch dependencies
# COPY pom.xml .
# RUN mvn dependency:go-offline

# Disable DevTools restart in Docker (volume mounts trigger false positives)
ENV SPRING_DEVTOOLS_RESTART_ENABLED=false

# Start command
CMD ["mvn", "spring-boot:run", "-Plocal"]
