# Dev image with Maven and JDK, full source code will be mounted
FROM maven:3.9-eclipse-temurin-17

WORKDIR /app

# Optional: pre-fetch dependencies if you want faster startup
COPY pom.xml .
RUN mvn dependency:go-offline

# Start command can be overridden in docker-compose
CMD ["mvn", "spring-boot:run", "-e"]
