spring:
  config:
    activate:
      on-profile: prod

  datasource:
    hikari:
      maximum-pool-size: 20

  jpa:
    properties:
      hibernate:
        format_sql: false   # Do not pretty-print SQL; reduces log size and overhead in production
    hibernate:
      ddl-auto: validate     # NEVER update in prod

server:
  tomcat:
    threads:
      max: 200
      min-spare: 20

    max-connections: 500
    accept-count: 100
    backlog: 100

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        orm:
          jdbc:
            bind: OFF

