spring:
  config:
    activate:
      on-profile: prod

  datasource:
    hikari:
      maximum-pool-size: 20

  data:
    redis:
      url: ${SPRING_DATA_REDIS_URL}
      timeout: 10s
      lettuce:
        pool:
          max-active: 16
          max-idle: 8

  jpa:
    properties:
      hibernate:
        format_sql: false   # Do not pretty-print SQL; reduces log size and overhead in production
        jdbc:
          batch_size: 20  # Batch size for bulk operations
    hibernate:
      ddl-auto: validate     # NEVER update in prod

server:
  port: ${PORT:8080}
  tomcat:
    threads:
      max: 200
      min-spare: 20

    max-connections: 500
    accept-count: 100
    backlog: 100

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        orm:
          jdbc:
            bind: OFF

app:
  aws:
    region: ${AWS_REGION}
    bucket-name: ${AWS_BUCKET_NAME}

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

  cookie:
    domain: ${COOKIE_DOMAIN}
    secure: true
