spring:
  application:
    name: springmate  # Sets the name of the Spring Boot application. Useful for identification in logs and admin tools.

  datasource:
    url: ${DB_URL} # JDBC URL to connect to the PostgreSQL database
    username: ${DB_USERNAME}  # Database username
    password: ${DB_PASSWORD}  # Database password
    driver-class-name: org.postgresql.Driver  # PostgreSQL JDBC driver class

  jpa:
    hibernate:
      ddl-auto: update  # Automatically updates the database schema. OK for dev.
    # database-platform: org.hibernate.dialect.PostgreSQLDialect  # Uncomment and fix if needed

  devtools:
    restart:
      enabled: true  # Enables automatic restart with Spring DevTools


  resilience4j.retry:
    instances:
      s3Upload:
        max-attempts: 3
        wait-duration: 1s

  resilience4j.circuitbreaker:
    instances:
      s3Upload:
        register-health-indicator: true
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
